### ISSUE TITLE
Internal error during connect: module 'toolhead' has no attribute 'BUFFER_TIME_HIGH'

### ISSUE THREAD

**Issue by MRX8024** [Annex-Engineering/TradRack#3]
Hi, I faced this problem on 11 klipper. What do you recommend other than updating?

  File "/home/klipper/klippy/extras/trad_rack.py", line 2256, in load_config
    return TradRack(config)
  File "/home/klipper/klippy/extras/trad_rack.py", line 41, in __init__
    self.tr_toolhead = TradRackToolHead(
  File "/home/klipper/klippy/extras/trad_rack.py", line 1742, in __init__
    self.move_queue.set_flush_time(toolhead.BUFFER_TIME_HIGH)

Thanks
-Maxim

**Comment by rsghosh** [comment]
If you switch to the `pre_toolhead_changes` branch I think it will work; the version of `trad_rack.py` on this branch is meant to be compatible with older versions of Klipper from before [commit bafb126](https://github.com/Klipper3d/klipper/commit/bafb126abd77edd0cb2e5ae3b5d99ff83272594c) (which was when `toolhead.BUFFER_TIME_HIGH` was added). You can switch to this branch using the following commands:
```
cd ~
./trad_rack_klippy_module/Klipper_Stuff/klippy_module/install.sh pre_toolhead_changes
sudo systemctl restart klipper
```
Let me know if this fixes it for you.

In the future, please use the `#tr_build_help` channel on the [Annex Discord server](https://discord.gg/MzTR3zE) for troubleshooting issues, as we have more people active there and you will likely get responses faster.

-Ryan

**Comment by MRX8024** [comment]
Yes, thanks, I replaced the program file and it helped. I've been using Tradrak for a long time, just wanted to update foruse Belay. Thanks for your hard work! I appreciate it/

-Maxim
