### ISSUE TITLE
Heat inserts too loose

### ISSUE THREAD

**Issue by dfosantos** [Annex-Engineering/TradRack#8]
M3 heat inserts usually have an outer diameter of 4.6mm.
Current diameter of the designed parts for the heat inserts is 4.7mm, which makes it too loose.

I suggest changing to 4.5mm, as tighter is better than loose. Heat insert can always melt the plastic.

**Comment by rsghosh** [comment]
The printed parts are designed for heat inserts with a 5.0mm outer diameter and 4.0mm length. You can find recommended sources for the inserts in the Trad Rack BOM/sourcing guide: https://docs.google.com/spreadsheets/d/1SKBtkgSVPqqGEjftI6v6i6T5Bh3Phx-4YXsJYH17ggs/edit?usp=sharing

(Vendors that sell parts for DIY 3D printers also often carry the same M3x5x4mm inserts as the AliExpress source from the guide)
